# Generated by Django 3.1.7 on 2021-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Globvar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prO', models.CharField(max_length=255, verbose_name='Правильный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('v2', models.CharField(max_length=255, verbose_name='Ответ 1')),
                ('v3', models.CharField(max_length=255, verbose_name='Ответ 2')),
                ('v4', models.CharField(max_length=255, verbose_name='Ответ 3')),
                ('v5', models.CharField(max_length=255, verbose_name='Ответ 4')),
                ('v6', models.CharField(max_length=255, verbose_name='Прав ответ')),
            ],
        ),
    ]
